package com.example.finhub.ui.components

import android.util.Log
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember

fun RandomFact(): String {
    val facts = listOf(
        "India’s first unicorn startup was InMobi, founded in 2007.",
        "Jio disrupted the Indian telecom industry in 2016, changing data pricing and competition.",
        "Zomato and Swiggy revolutionized food delivery in India, making online food ordering mainstream.",
        "Flipkart, founded in 2007, was acquired by Walmart for $16 billion in 2018.",
        "Ola Cabs started as an online cab aggregator and grew to dominate India’s ride-hailing market.",
        "Paytm began as a mobile recharge platform in 2010 and became a full-fledged financial services company.",
        "BYJU’S is one of the largest ed-tech firms globally, with over 100 million users.",
        "TCS (Tata Consultancy Services) is India’s largest IT services company, valued over $200 billion.",
        "India’s first IPO was by DCM in 1947.",
        "Airbnb began with air mattresses and now has a global presence, including India.",
        "India is home to over 90,000 registered startups as of 2024, with 20+ unicorns.",
        "Ratan Tata played a significant role in expanding Tata Group companies like Tata Motors and TCS.",
        "Reliance Industries, founded by Dhirubhai Ambani, is one of India’s largest conglomerates.",
        "OYO, started as Oravel Stays in 2013, disrupted the budget hotel sector and expanded globally.",
        "Indian startups raised over $10 billion in venture capital funding in 2021.",
        "In 2019, India’s GDP crossed $2.7 trillion, becoming the world’s fifth-largest economy.",
        "Tata Nano, launched in 2008, was dubbed the world’s cheapest car at ₹1 lakh ($2000).",
        "Myntra started as an online fashion retailer and was acquired by Flipkart in 2014.",
        "Zomato started as a restaurant review website in 2008 before evolving into a food delivery giant.",
        "Venture capital in India has rapidly grown, especially in ed-tech, fintech, and SaaS sectors.",
        "India’s startup ecosystem has grown immensely, with Bengaluru known as the 'Silicon Valley of India.'",
        "Shark Tank India has brought public attention to Indian entrepreneurship.",
        "CRED, founded by Kunal Shah, rewards users for paying credit card bills on time.",
        "BharatPe enables merchants to accept QR payments and access small business loans.",
        "India’s gig economy is growing with platforms like Uber, Swiggy, and UrbanClap offering flexible jobs.",
        "Snapdeal was once a top rival to Flipkart and Amazon, now focusing on niche markets.",
        "Flipkart is India’s largest e-commerce company, with Amazon close behind.",
        "Wipro is a top Indian IT services provider, known for its sustainability efforts.",
        "India saw a record 20 million new demat accounts opened in 2020.",
        "India's first ATM was installed in Mumbai in 1987 by HSBC.",
        "The ₹ symbol was officially adopted in 2010, combining Devanagari 'Ra' and Latin 'R'.",
        "The first Indian bank, Bank of Hindustan, was established in 1770.",
        "The Reserve Bank of India (RBI) was established in 1935 and nationalized in 1949.",
        "India's first stock exchange, the Bombay Stock Exchange (BSE), was founded in 1875.",
        "The Securities and Exchange Board of India (SEBI) was established in 1988 and given statutory powers in 1992.",
        "The ₹10,000 note was the highest denomination printed in India, last issued in 1978.",
        "Indian coins have mint marks: Mumbai (⧫), Kolkata (no mark), Hyderabad (★), and Noida (●).",
        "Dalal Street in Mumbai is synonymous with Indian financial markets, like Wall Street in the U.S.",
        "India’s first post-independence budget was presented on November 26, 1947, by R.K. Shanmukham Chetty.",
        "Indira Gandhi was the first and only woman to present the Union Budget in 1970.",
        "The Halwa Ceremony marks the beginning of the Union Budget printing process.",
        "The Railway Budget was merged with the Union Budget in 2017 after 92 years.",
        "The Jan Dhan Yojana set a world record by opening over 18 million bank accounts in one week.",
        "India’s first credit card was introduced by Central Bank of India in 1980.",
        "The National Stock Exchange (NSE) was established in 1992 and is among the world’s largest.",
        "The ₹1 note is the only Indian currency signed by the Finance Secretary, not the RBI Governor.",
        "Polymer ₹10 notes were trialed by the RBI in 2013 to increase durability.",
        "India’s first mutual fund was launched by UTI in 1963.",
        "SEWA Bank in Ahmedabad pioneered microfinance in India in 1974.",
        "India’s first dematerialized (Demat) account was introduced in 1996.",
        "The BSE Sensex was launched in 1986 with a base value of 100.",
        "The RBI logo features a tiger and a palm tree, symbolizing strength and prosperity.",
        "Hawala refers to informal money transfer systems without physical movement.",
        "The first Indian coin was issued in the 6th century BCE during the Mahajanapadas.",
        "The Banking Ombudsman Scheme was introduced by the RBI in 1995.",
        "India’s first mobile banking service was launched by ICICI Bank in 2008.",
        "The ₹2,000 note introduced post-demonetization in 2016 is being phased out since 2023.",
        "The Chakra on Indian currency notes represents the Ashoka Pillar, symbolizing law and dharma.",
        "The RBI's headquarters moved from Kolkata to Mumbai in 1937, where it remains today.",
        "The first paper money was issued in China over 1,000 years ago during the Tang Dynasty.",
        "Visa was originally launched in 1958 as 'BankAmericard' by Bank of America.",
        "The term 'piggy bank' comes from 'pygg,' a type of clay used in old English money jars.",
        "The first credit card transaction was made at a New York restaurant in 1950.",
        "Indian UPI (Unified Payments Interface) processes over 10 billion transactions monthly, revolutionizing digital payments.",
        "The first coins were minted in Lydia (modern-day Turkey) around 600 BCE.",
        "Bartering, the direct exchange of goods and services, predates the invention of money.",
        "The word 'salary' originates from 'salarium,' money given to Roman soldiers to buy salt.",
        "The U.S. Secret Service was originally established in 1865 to combat counterfeit currency.",
        "The first ATM was installed in London in 1967 and used paper vouchers instead of plastic cards.",
        "The U.S. dollar is the most widely used currency in global transactions.",
        "The Euro is the second most traded currency in the world.",
        "The world's first banknotes were issued in China during the Tang Dynasty.",
        "The first check was written in 1659 in England.",
        "The term 'bankrupt' comes from the Italian 'banca rotta,' meaning broken bench.",
        "The first stock exchange was established in Amsterdam in 1602.",
        "The concept of insurance dates back to ancient Babylonian times.",
        "The first known use of coins was in the ancient kingdom of Lydia.",
        "The term 'credit' comes from the Latin 'credere,' meaning to believe or trust.",
        "The first recorded use of a promissory note was in China during the Tang Dynasty.",
        "The first central bank was the Swedish Riksbank, established in 1668.",
        "The gold standard, linking currency value to gold, was widely used in the 19th and early 20th centuries.",
        "The first U.S. coins were minted in 1793.",
        "The first U.S. paper money was issued in 1861 to finance the Civil War.",
        "The term 'buck' as slang for money comes from buckskins used in trade.",
        "The first use of the dollar sign '$' was in the 1770s.",
        "The first credit card was introduced by Diners Club in 1950.",
        "The first debit card was introduced in the U.S. in the 1980s.",
        "The first mobile payment was made in Finland in 1997.",
        "The first cryptocurrency, Bitcoin, was introduced in 2009.",
        "The first recorded use of compound interest dates back to ancient Babylon.",
        "The concept of microfinance was pioneered by Muhammad Yunus in Bangladesh.",
        "The first mutual fund was established in the Netherlands in 1774.",
        "The first hedge fund was created by Alfred Winslow Jones in 1949.",
        "The first exchange-traded fund (ETF) was introduced in Canada in 1990.",
        "The first U.S. ETF was launched in 1993.",
        "The term 'bull market' refers to rising prices, while 'bear market' indicates falling prices.",
        "The first recorded use of the term 'bull market' was in the 18th century.",
        "The first recorded use of the term 'bear market' was in the early 18th century.",
        "The first known use of the term 'inflation' in an economic context was in the 19th century.",
        "The first recorded hyperinflation occurred in France during the French Revolution.",
        "The Weimar Republic experienced one of the worst hyperinflations in history in the 1920s.",
        "Zimbabwe experienced hyperinflation in the late 2000s, with prices doubling every day.",
        "The first recorded use of the term 'deflation' was in the 19th century.",
        "The Great Depression of the 1930s was marked by severe deflation.",
        "The first recorded financial crisis was the Tulip Mania in the Netherlands in the 1630s.",
        "The South Sea Bubble of 1720 was one of the earliest stock market crashes.",
        "The Wall Street Crash of 1929 led to the Great Depression.",
        "The 2008 financial crisis was triggered by the collapse of the housing bubble in the U.S.",
        "The term 'quantitative easing' refers to central banks injecting money into the economy.",
        "The first use of quantitative easing was by the Bank of Japan in the early 2000s.",
        "The Federal Reserve was established in 1913 as the central bank of the U.S.",
        "The Bank of England, founded in 1694, is the second oldest central bank.",
        "The International Monetary Fund (IMF) was established in 1944 to promote global financial stability.",
        "The World Bank was also established in 1944 to provide financial assistance to developing countries.",
        "The Bretton Woods system established fixed exchange rates in 1944.",
        "The Bretton Woods system collapsed in the early 1970s, leading to floating exchange rates.",
        "The first credit bureau was established in the U.S. in the 1890s.",
        "Credit scores are used to assess an individual's creditworthiness.",
        "The FICO score, developed in 1989, is widely used in the U.S.",
        "The concept of compound interest is often called the 'eighth wonder of the world.'",
        "The Rule of 72 is a simple way to estimate how long an investment will take to double.",
        "The first recorded use of a check was in the 9th century in the Islamic world.",
        "The first modern banknotes were issued in Sweden in the 1660s.",
        "The first recorded use of a bank was in ancient Mesopotamia.",
        "The New York Stock Exchange (NYSE) was founded in 1792.",
        "Warren Buffett bought his first stock at age 11.",
        "The Indian stock market dates back to 1875 with the Bombay Stock Exchange.",
        "The word 'salary' comes from 'salarium,' money paid to Roman soldiers to buy salt.",
        "Compound interest was called the 'eighth wonder of the world' by Albert Einstein.",
        "Credit cards were first used in the 1950s.",
        "The world's first paper money was created in China over 1,000 years ago.",
        "Jeff Bezos started Amazon in a garage in 1994.",
        "The U.S. dollar is used in more than 10 countries outside the U.S.",
        "Inflation reduces the value of money over time.",
        "The richest man in modern history was Mansa Musa, emperor of Mali in the 14th century.",
        "A bear market means falling prices; a bull market means rising prices.",
        "Bitcoin’s first real-world transaction was for two pizzas in 2010.",
        "The global derivatives market is worth over $1 quadrillion.",
        "Only about 10% of the world’s money exists in physical cash.",
        "The concept of insurance dates back to ancient Babylon.",
        "Microfinance empowers low-income people by offering small loans.",
        "The Indian Rupee symbol ₹ was adopted in 2010.",
        "Bartering was the earliest form of commerce before money was invented.",
        "Black Friday originally referred to a financial crisis, not shopping deals.",
        "The U.S. once issued a $100,000 bill featuring Woodrow Wilson, used only for Federal Reserve transactions.",
        "In 1946, Hungary printed a 100 quintillion pengő note—the largest denomination ever issued.",
        "A 1943 U.S. penny mistakenly minted in copper sold for over $1 million due to its rarity.",
        "Pablo Escobar reportedly lost about $1 billion annually to rats nibbling on his hidden cash stashes.",
        "The term 'budget' originates from the French word 'bougette,' meaning a small bag.",
        "The $2 bill is still legal tender in the U.S., though many believe it's rare or out of circulation.",
        "The grooves on coin edges were designed to prevent shaving off precious metals—a common practice in the past.",
        "The first ATM was installed in London in 1967 and used paper vouchers instead of plastic cards.",
        "The phrase 'In God We Trust' was first added to U.S. currency in 1963.",
        "The term 'piggy bank' comes from 'pygg,' a type of clay used in old English money jars.",
        "The first credit card transaction occurred at a New York restaurant in 1950.",
        "The U.S. Secret Service was originally established in 1865 to combat counterfeit currency.",
        "The first coins were minted in Lydia (modern-day Turkey) around 600 BCE.",
        "The term 'bankrupt' comes from the Italian 'banca rotta,' meaning broken bench.",
        "The first stock exchange was established in Amsterdam in 1602.",
        "The first known use of coins was in the ancient kingdom of Lydia.",
        "The first recorded use of a promissory note was in China during the Tang Dynasty.",
        "The word 'entrepreneur' comes from the French word entreprendre, meaning 'to undertake.'",
        "India's Dabbawala system has a 99.99% accuracy rate in lunch delivery.",
        "The Mumbai tiffin service was studied by Harvard Business School.",
        "Amazon’s logo has an arrow from A to Z, symbolizing it sells everything.",
        "The first banner ad ever clicked had a 44% click-through rate.",
        "IKEA names products after Swedish towns and people.",
        "Warren Buffett bought his first stock at age 11.",
        "McDonald's once made bubblegum-flavored broccoli to appeal to kids.",
        "Google's first office was a garage in California.",
        "Infosys was started with ₹10,000 borrowed from the founder’s wife.",
        "The term 'unicorn' was coined in 2013 by venture capitalist Aileen Lee.",
        "YouTube was originally a dating site.",
        "Paytm’s name stands for 'Pay Through Mobile.'",
        "Domino’s Pizza was almost named 'Dominick’s.'",
        "Google rents goats to cut its lawn.",
        "The average CEO reads 60 books a year.",
        "The founder of Nike was a track athlete and coach.",
        "The first product sold on Amazon was a book.",
        "KFC’s founder started the franchise at age 65.",
        "The term 'freelancer' originated from medieval mercenary knights.",
        "FedEx was originally funded by casino winnings.",
        "Coca-Cola was first sold as a medicinal tonic.",
        "Airbnb once sold Obama and McCain-themed cereal boxes to raise money.",
        "Slack was created as a byproduct of a failed video game.",
        "Zoom saw 30x growth during the 2020 pandemic.",
        "Apple almost merged with Pepsi in the 1980s.",
        "Starbucks uses round tables to make customers feel less alone.",
        "The word 'salary' comes from sal, Latin for salt — once used for payment.",
        "Reddit was initially populated by fake users.",
        "Burger King once offered a meat-scented cologne in Japan.",
        "The word 'brand' comes from Norse brandr, meaning 'to burn.'",
        "A business card in Japan is treated with high respect and etiquette.",
        "Shopify started as a snowboard equipment store.",
        "Google's first storage was built from LEGO bricks.",
        "There are over 90,000 registered startups in India as of 2024.",
        "Dhirubhai Ambani started Reliance from a one-room office.",
        "Zappos once sent a customer flowers after a late shipment.",
        "The founder of Zoom was rejected by Visa multiple times.",
        "Netflix once offered to sell itself to Blockbuster for $50M — and was rejected.",
        "Bumble was founded by a former Tinder executive.",
        "India has the third-largest number of unicorns globally.",
        "The most expensive domain ever sold is Cars.com for $872 million.",
        "LinkedIn was created before Facebook.",
        "D-Mart’s founder is a former stockbroker.",
        "TikTok was the most downloaded app of 2022.",
        "Starbucks spends more on employee training than advertising.",
        "Canva was started by a teacher in Australia.",
        "Lenskart began by selling prescription glasses online.",
        "Business tycoon Ratan Tata drives his own cars.",
        "Walmart once had live bands to attract customers."
    )

    return facts.random()
}